### ISSUE TITLE
last language select does not come back

### ISSUE THREAD

**Issue by Productivix** [0xClpz/i18next-react-native-async-storage#10]
hi, 
good package , but when I call it as you describe with the codes : 
`
i18n.use(AsyncStoragePlugin());

i18n.use(initReactI18next).init({
  /*     lng - default language
    fallbackLng - Fallback language in case key is not found for any translation.
    resources - JSON file for various languages. */
  compatibilityJSON: 'v3', // <--- add this line.
  fallbackLng: 'fr',
  //lng: 'fr',

  //supportedLngs: ['en', 'fr', 'de'],
  // have a initial namespace
  ns: ['common', 'app'],
  defaultNS: 'common',

  resources: {
    en: en,
    de: de,
    fr: fr,
  },
  interpolation: {
    escapeValue: false, // react already safes from xss
  },
});
`
if I stop my app in language 'de' , I reload this app and I always get the 'fr' language (may be the fallback choice that I need),
If I comment this : //fallbackLng: 'fr', I will get 'en'== the 1st of ressources , 

I would have expected to recover a 'de' language version ?

my stack : 
 "i18next": "^21.9.1",
    "i18next-react-native-async-storage": "^1.0.4",
    "react": "18.0.0",
    "react-i18next": "^11.18.4",
    "react-native": "0.69.4",
thanks

**Comment by ruiaraujo012** [comment]
I have the same issue.

How did you resolve that?

**Comment by Productivix** [comment]
I do not use it anymore : that is the solution

**Comment by ruiaraujo012** [comment]
> I do not use it anymore : that is the solution

You're right, I end up making my own language detector and persisting the data to async storage.
